name = "Trajectories"
uuid = "2c80a279-213e-54d7-a557-e9a14725db56"
repo = "https://github.com/mschauer/Trajectories.jl.git"
version = "0.2.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
RecipesBase = "0.7, 0.8"
Tables = "0.2"
julia = "1"
